#!/usr/bin/env bash
#
# Agent Universe gsn-daemon + desktop connector installer for macOS / Linux.
#
# What it does (idempotent, per-user, no sudo):
#   1. Installs the gsn-daemon binary for v3.5.0:
#        - Linux x86_64  : downloads the prebuilt tarball from the GitHub release
#        - macOS / other : builds from source with cargo (NO darwin prebuilt asset yet)
#   2. Generates a persistent MCP bearer token (unless one is provided).
#   3. Writes a runnable start script and prints the exact connector values
#      (HTTP URL + Authorization header) for DeepSeek Harness and Doubao desktop.
#
# It never moves git tags, never publishes, and only downloads over HTTPS.
#
# Environment overrides:
#   AU_VERSION=v3.5.0   AU_HOME=$HOME/.agent-universe   MCP_BEARER_TOKEN=...
#   AU_PORT=4002        AU_SKIP_BUILD=1                 AU_FORCE_BUILD=1
#
set -euo pipefail

OWNER="TwinsEarth"
REPO="agent-universe"
VERSION="${AU_VERSION:-v3.5.0}"
STRIP="${VERSION#v}"                       # 3.5.0
HOME_DIR="${AU_HOME:-$HOME/.agent-universe}"
BIN_DIR="$HOME_DIR/bin"
DATA_DIR="$HOME_DIR/data"
PORT="${AU_PORT:-4002}"
LISTEN="${AU_LISTEN:-127.0.0.1}"
TOKEN="${MCP_BEARER_TOKEN:-}"
MODE="${AU_MODE:-light}"

RED=$'\033[31m'; GREEN=$'\033[32m'; YEL=$'\033[33m'; BLD=$'\033[1m'; OFF=$'\033[0m'
say(){ printf '%s\n' "$*"; }
ok(){ printf '%s✓ %s%s\n' "$GREEN" "$*" "$OFF"; }
warn(){ printf '%s! %s%s\n' "$YEL" "$*" "$OFF"; }
die(){ printf '%s✗ %s%s\n' "$RED" "$*" "$OFF" >&2; exit 1; }

need(){ command -v "$1" >/dev/null 2>&1 || die "required tool not found: $1"; }

OS="$(uname -s)"; ARCH="$(uname -m)"
case "$OS" in
  Darwin) PLATFORM="macos" ;;
  Linux)  PLATFORM="linux" ;;
  *) die "unsupported OS: $OS (use install.ps1 on Windows)" ;;
esac

mkdir -p "$BIN_DIR" "$DATA_DIR"

# ---------------------------------------------------------------------------
# 1. Obtain gsn-daemon
# ---------------------------------------------------------------------------
BIN_PATH="$BIN_DIR/gsn-daemon"

build_from_source() {
  need cargo; need git
  local src="$HOME_DIR/src/agent-universe"
  say "Building gsn-daemon $VERSION from source (first build takes a few minutes)..."
  if [ -d "$src/.git" ]; then
    git -C "$src" fetch --tags --quiet
    git -C "$src" checkout --quiet "$VERSION"
  else
    mkdir -p "$HOME_DIR/src"
    git clone --quiet --depth 1 --branch "$VERSION" \
      "https://github.com/$OWNER/$REPO.git" "$src"
  fi
  ( cd "$src" && cargo build --release -p gsn-core --locked )
  local built
  built="$(find "$src/target/release" -maxdepth 1 -type f -name 'gsn-daemon' | head -1)"
  [ -n "$built" ] || die "build finished but gsn-daemon binary not found"
  cp "$built" "$BIN_PATH"
  chmod +x "$BIN_PATH"
}

if [ "$PLATFORM" = "linux" ] && [ "$ARCH" = "x86_64" ] && [ "${AU_FORCE_BUILD:-0}" != "1" ]; then
  if [ -x "$BIN_PATH" ] && [ "${AU_SKIP_BUILD:-0}" = "1" ]; then
    ok "existing gsn-daemon kept ($BIN_PATH)"
  else
    need curl
    ASSET="gsn-daemon-linux-x64-${VERSION}.tar.gz"
    URL="https://github.com/$OWNER/$REPO/releases/download/$VERSION/$ASSET"
    tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
    say "Downloading $ASSET ..."
    curl -fL --retry 3 -o "$tmp/d.tgz" "$URL" || die "download failed: $URL"
    tar -xzf "$tmp/d.tgz" -C "$tmp"
    found="$(find "$tmp" -type f -name 'gsn-daemon' | head -1)"
    [ -n "$found" ] || die "gsn-daemon not found inside $ASSET"
    install -m 0755 "$found" "$BIN_PATH"
  fi
else
  # macOS (no darwin prebuilt in this release) or non-x64 Linux -> build.
  if [ -x "$BIN_PATH" ] && [ "${AU_FORCE_BUILD:-0}" != "1" ]; then
    ok "existing gsn-daemon kept ($BIN_PATH); set AU_FORCE_BUILD=1 to rebuild"
  else
    warn "No prebuilt daemon for $PLATFORM/$ARCH in $VERSION; building from source."
    build_from_source
  fi
fi
"$BIN_PATH" --version >/dev/null 2>&1 || "$BIN_PATH" -V >/dev/null 2>&1 || true
ok "gsn-daemon installed at $BIN_PATH"

# ---------------------------------------------------------------------------
# 2. Token
# ---------------------------------------------------------------------------
TOKEN_FILE="$HOME_DIR/mcp.token"
if [ -z "$TOKEN" ]; then
  if [ -f "$TOKEN_FILE" ]; then
    TOKEN="$(cat "$TOKEN_FILE")"
  else
    need openssl
    TOKEN="$(openssl rand -hex 32)"
    umask 077; printf '%s' "$TOKEN" > "$TOKEN_FILE"
    ok "generated new MCP bearer token -> $TOKEN_FILE"
  fi
else
  umask 077; printf '%s' "$TOKEN" > "$TOKEN_FILE"
fi

# ---------------------------------------------------------------------------
# 3. Start script
# ---------------------------------------------------------------------------
START="$BIN_DIR/start-daemon.sh"
cat > "$START" <<EOF
#!/usr/bin/env bash
# Generated by install.sh for $VERSION. Edit the port/mode as needed.
set -euo pipefail
export MCP_BEARER_TOKEN="\$(cat '$TOKEN_FILE')"
exec "$BIN_PATH" --listen "$LISTEN" --api-port "$PORT" --data-dir "$DATA_DIR" --mode "$MODE"
EOF
chmod +x "$START"
ok "start script -> $START"

MCP_URL="http://127.0.0.1:$PORT/api/v1/mcp"

cat <<EOM

${BLD}Agent Universe daemon $VERSION is ready.${OFF}

Start it with:
    $START
    # or:  MCP_BEARER_TOKEN=... gsn-daemon --listen 127.0.0.1 --api-port $PORT --mode light

${BLD}Connect an MCP client${OFF} (Streamable HTTP, no stdio bridge needed):

  Endpoint (URL): $MCP_URL
  Header:         Authorization: Bearer $TOKEN

  - DeepSeek Harness: install the @twinsearth/agent-universe-harness bundle,
    or use connectors/examples/cordis.patch.agent-universe.yml. Set env
    MCP_BEARER_TOKEN before launching dsh.
  - Doubao desktop: add a custom HTTP connector with the URL/header above
    (connectors/examples/doubao-connector.json).
  - Any stdio-only MCP host: npx @twinsearth/agent-universe-mcp
    (AGENT_UNIVERSE_MCP_URL / AGENT_UNIVERSE_MCP_TOKEN).

Read-only tools work without a token only if the daemon is started WITHOUT
MCP_BEARER_TOKEN; write/money tools are always fail-closed.
EOM
