<#
.SYNOPSIS
  Agent Universe gsn-daemon + desktop connector installer for Windows.

.DESCRIPTION
  Per-user, idempotent, no admin required:
    1. Downloads/extracts the prebuilt gsn-daemon (gsn-daemon-x86_64-pc-windows-msvc.zip, v3.5.0).
    2. Generates a persistent MCP bearer token (unless MCP_BEARER_TOKEN is set).
    3. Writes start-daemon.ps1 and prints the exact HTTP connector URL + header
       for DeepSeek Harness and Doubao desktop.

  Overrides (env): AU_VERSION=v3.5.0, AU_HOME=$env:USERPROFILE\.agent-universe,
                   AU_PORT=4002, MCP_BEARER_TOKEN=...

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File .\install.ps1
#>
[CmdletBinding()]
param(
  [string]$Version = $(if ($env:AU_VERSION) { $env:AU_VERSION } else { 'v3.5.0' }),
  [int]$Port    = $(if ($env:AU_PORT)    { [int]$env:AU_PORT } else { 4002 }),
  [string]$Mode  = $(if ($env:AU_MODE)    { $env:AU_MODE } else { 'light' })
)

$ErrorActionPreference = 'Stop'
$Owner = 'TwinsEarth'
$Repo  = 'agent-universe'
$HomeDir = if ($env:AU_HOME) { $env:AU_HOME } else { Join-Path $env:USERPROFILE '.agent-universe' }
$BinDir  = Join-Path $HomeDir 'bin'
$DataDir = Join-Path $HomeDir 'data'
New-Item -ItemType Directory -Force -Path $BinDir, $DataDir | Out-Null

function Fail($m){ Write-Error $m; exit 1 }

# 1. Download + extract ------------------------------------------------------
$asset = 'gsn-daemon-x86_64-pc-windows-msvc.zip'
$url   = "https://github.com/$Owner/$Repo/releases/download/$Version/$asset"
$zip   = Join-Path $env:TEMP "gsn-daemon-$Version.zip"

Write-Host "Downloading $asset ($Version) ..."
try {
  [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
  Invoke-WebRequest -Uri $url -OutFile $zip -UseBasicParsing
} catch { Fail "download failed: $url`n$_" }

$extract = Join-Path $env:TEMP "gsn-daemon-$Version"
if (Test-Path $extract) { Remove-Item -Recurse -Force $extract }
Expand-Archive -Path $zip -DestinationPath $extract -Force

$exe = Get-ChildItem -Path $extract -Recurse -File -Filter 'gsn-daemon.exe' | Select-Object -First 1
if (-not $exe) { Fail "gsn-daemon.exe not found inside $asset" }
$dest = Join-Path $BinDir 'gsn-daemon.exe'
Copy-Item -Force $exe.FullName $dest
Write-Host "✓ installed $dest"

# 2. Token -------------------------------------------------------------------
$tokenFile = Join-Path $HomeDir 'mcp.token'
$token = $env:MCP_BEARER_TOKEN
if (-not $token) {
  if (Test-Path $tokenFile) {
    $token = (Get-Content -Raw $tokenFile).Trim()
  } else {
    $bytes = New-Object byte[] 32
    [Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $token = -join ($bytes | ForEach-Object { $_.ToString('x2') })
    [IO.File]::WriteAllText($tokenFile, $token, (New-Object Security.AccessControl.FileSecurity))
    Write-Host "✓ generated MCP bearer token -> $tokenFile"
  }
} else {
  [IO.File]::WriteAllText($tokenFile, $token)
}

# 3. Start script ------------------------------------------------------------
$start = Join-Path $BinDir 'start-daemon.ps1'
$startBody = @"
# Generated by install.ps1 for $Version.
`$ErrorActionPreference = 'Stop'
`$env:MCP_BEARER_TOKEN = (Get-Content -Raw '$tokenFile').Trim()
& '$dest' --listen 127.0.0.1 --api-port $Port --data-dir '$DataDir' --mode '$Mode'
"@
[IO.File]::WriteAllText($start, $startBody)
Write-Host "✓ start script -> $start"

$mcpUrl = "http://127.0.0.1:$Port/api/v1/mcp"
Write-Host @"

Agent Universe daemon $Version is ready.

Start it with:
    powershell -ExecutionPolicy Bypass -File "$start"

Connect an MCP client (Streamable HTTP, no stdio bridge needed):
  Endpoint (URL): $mcpUrl
  Header:         Authorization: Bearer $token

  - Doubao desktop: custom HTTP connector (connectors/examples/doubao-connector.json)
  - DeepSeek Harness: @twinsearth/agent-universe-harness bundle, or
    connectors/examples/cordis.patch.agent-universe.yml (set MCP_BEARER_TOKEN)
  - stdio-only host: npx @twinsearth/agent-universe-mcp
"@
